# Generated by Django 4.0.4 on 2022-05-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Department_Master',
            },
        ),
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('st_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('st_age', models.IntegerField()),
                ('st_mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('st_reg_date', models.DateField(blank=True, null=True)),
                ('st_fk_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.department_master')),
            ],
        ),
    ]
